### ISSUE TITLE
Cannot look at logs

### ISSUE THREAD

**Issue by maxnoe** [fact-project/shifthelper_webinterface#27]

**Comment by dneise** [comment]
Not only for Safari. On my Ubuntu it also does not work.

This is how it looks for me:

![2017-07-17-174506_1920x1080_scrot](https://user-images.githubusercontent.com/8200858/28276628-c7ae86e2-6b17-11e7-898a-c6f6729762fa.png)


This is what the logs say
~~~
7/17/2017 5:41:26 PM[2017-07-17 15:41:26 +0000] [34] [ERROR] Socket error processing request.
7/17/2017 5:41:26 PMTraceback (most recent call last):
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/workers/async.py", line 66, in handle
7/17/2017 5:41:26 PM    six.reraise(*sys.exc_info())
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/six.py", line 625, in reraise
7/17/2017 5:41:26 PM    raise value
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/workers/async.py", line 56, in handle
7/17/2017 5:41:26 PM    self.handle_request(listener_name, req, client, addr)
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/workers/async.py", line 129, in handle_request
7/17/2017 5:41:26 PM    six.reraise(*sys.exc_info())
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/six.py", line 625, in reraise
7/17/2017 5:41:26 PM    raise value
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/gunicorn/workers/async.py", line 114, in handle_request
7/17/2017 5:41:26 PM    for item in respiter:
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/werkzeug/wsgi.py", line 703, in __next__
7/17/2017 5:41:26 PM    return self._next()
7/17/2017 5:41:26 PM  File "/opt/conda/lib/python3.5/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
7/17/2017 5:41:26 PM    for item in iterable:
7/17/2017 5:41:26 PM  File "/home/fact/shifthelper_webinterface/__init__.py", line 120, in generate
7/17/2017 5:41:26 PM    with open(app.config['shifthelper_log']) as f:
7/17/2017 5:41:26 PMFileNotFoundError: [Errno 2] No such file or directory: 'test.log'
~~~

It looks for a file named: `test.log` while in our configuration repo it says:

~~~
	"app": {
		"secret_key": XXX,
		"user": "fact",
		"password": XXX,
                "shifthelper_log": "/logs/shifthelper.log"
~~~

could the config be modified in the TU-dortmund infrastrucutre nodes?

**Comment by dneise** [comment]
This was an error during deployment. @MaxNoe fixed it
